version: "3"
services:
  notes:
    build: .
    volumes:
      - type: bind
        source: .
        target: /workdir
    ports:
      - 8989:8989
    command: jupyter lab --ip=0.0.0.0 --port=8989 --allow-root --no-browser --ServerApp.password='sha1:e131964f03ee:745d1a91857a25bc46dd4404ecb9010d1ab9cfed'
