[project]
name = "notes"
version = "0.1.0"
description = "my notebook"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "jupyter-book>=1.0.4.post1",
    "jupyter-copilot>=0.1.5",
    "jupyterlab<4.0.0",
    "jupyterlab-lsp>=4.3.0",
]
