# Jekyll configration
name: 盆暗の学習記録
description: データサイエンスやソフトウェア開発、およびそれらをビジネスに活かすことについて学んだことをメモしていく予定です。
theme: jekyll-theme-leap-day
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
